apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connect
  namespace: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connect
  template:
    metadata:
      labels:
        app: debezium-connect
    spec:
      containers:
      - name: debezium
        image: quay.io/debezium/connect:latest
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"       # 🔥 Paru-paru 2 Core
            memory: "4Gi"  # 🔥 Napas lega 4 GB RAM anti OOMKilled
        ports:
        - containerPort: 8083
        env:
        - name: BOOTSTRAP_SERVERS
          value: "redpanda-cluster-0.redpanda-cluster.redpanda.svc.cluster.local:9093"
        - name: GROUP_ID
          value: "debezium-cluster"
        - name: CONFIG_STORAGE_TOPIC
          value: "debezium-configs"
        - name: OFFSET_STORAGE_TOPIC
          value: "debezium-offsets"
        - name: STATUS_STORAGE_TOPIC
          value: "debezium-status"
---
apiVersion: v1
kind: Service
metadata:
  name: debezium-connect-svc
  namespace: redpanda
spec:
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app: debezium-connect