---
# 1. Persistent Volume Claim (Biar data DB kaga amblas pas Pod restart)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-metadata-pvc
  namespace: uds-production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# 2. Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-metadata
  namespace: uds-production
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-metadata

---
# 3. ConfigMap (Script sakti buat nge-create DB dan User ClearML)
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: uds-production
data:
  init.sql: |
    CREATE USER clearml_admin WITH ENCRYPTED PASSWORD 'clearml_super_secret';
    CREATE DATABASE clearml_db;
    GRANT ALL PRIVILEGES ON DATABASE clearml_db TO clearml_admin;
    ALTER DATABASE clearml_db OWNER TO clearml_admin;

---
# 4. Deployment Postgres 15 Alpine
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-metadata
  namespace: uds-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-metadata
  template:
    metadata:
      labels:
        app: postgres-metadata
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "super_secret_root_password" # Password root/postgres
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: postgres-metadata-pvc
        - name: init-scripts
          configMap:
            name: postgres-init-script