# =====================================================================
# BENTOML SERVING VALUES (XGBOOST FRAUD DETECTION)
# =====================================================================
# 🔥 FIX: Nyalakan PostgreSQL bawaan agar Yatai tidak CrashLoopBackOff
postgresql:
  enabled: true
  auth:
    username: yatai
    password: yatai_secret_password
    database: yatai

deployment:
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi

runners:
  # Limit runner XGBoost biar kaga rakus CPU
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi