# =====================================================================
# BENTOML SERVING VALUES (XGBOOST FRAUD DETECTION)
# =====================================================================
postgresql:
  enabled: false # 🔥 FIX: Matikan Postgres bawaan Helm penyebab CrashLoopBackOff

# 🔥 FIX: Ganti ke externalPostgresql biar BentoML kaga nyari di localhost
externalPostgresql:
  host: "postgres-metadata.uds-production.svc.cluster.local"
  port: 5432
  username: "yatai"
  password: "yatai_secret_password"
  database: "yatai"

deployment:
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi

runners:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi