# =====================================================================
# FEAST FEATURE STORE VALUES
# =====================================================================
featureServer:
  enabled: true
  replicaCount: 1
  image:
    repository: feastdev/feature-server
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  
  # Inject koneksi Redis sebagai Online Store
  env:
    - name: FEAST_REDIS_HOST
      value: "redis-master.uds-production.svc.cluster.local"
    - name: FEAST_REDIS_PORT
      value: "6379"