# ==========================================
# GRAFANA ENTERPRISE DASHBOARD CONFIGURATION
# ==========================================
adminPassword: "admin"

persistence:
  enabled: true
  type: pvc
  storageClassName: "local-path"
  size: 2Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      # 🔥 NAMESPACE UPDATED: emarkrtz-production -> uds-production
      url: http://prometheus-server.uds-production.svc.cluster.local
      access: proxy
      isDefault: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi