# ==========================================
# GRAFANA ENTERPRISE DASHBOARD (EKS)
# ==========================================
adminPassword: "admin"

persistence:
  enabled: true
  type: pvc
  storageClassName: "gp2"
  size: 5Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.uds-production.svc.cluster.local
      access: proxy
      isDefault: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi