# =====================================================================
# METABASE VALUES - BUSINESS INTELLIGENCE (AWS EKS OPTIMIZED)
# =====================================================================
replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 2Gi

extraEnv:
  - name: JAVA_OPTS
    value: "-Xmx768m"

service:
  type: ClusterIP # Better security in AWS VPC
  port: 80