# =====================================================================
# MLFLOW MODEL REGISTRY VALUES
# =====================================================================
backendStore:
  postgres:
    enabled: false # 🔥 FIX: Matikan subchart bawaan yang cacat
    host: "postgres-metadata.uds-production.svc.cluster.local"
    port: 5432
    user: "mlflow_admin"
    password: "mlflow_super_secret"
    database: "mlflow_db"
    
artifactRoot:
  s3:
    enabled: true
    bucket: "uds-enterprise-datalake-2026"
    path: "mlflow-artifacts"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi