# =====================================================================
# MLFLOW MODEL REGISTRY VALUES
# =====================================================================
backendStore:
  postgres:
    enabled: false
    host: "postgres-metadata.uds-production.svc.cluster.local"
    port: 5432
    user: "mlflow_admin"
    password: "mlflow_super_secret"
    database: "mlflow_db"
    
artifactRoot:
  s3:
    enabled: true
    bucket: "uds-enterprise-datalake-2026"
    path: "mlflow-artifacts"

extraEnvVars:
  GUNICORN_CMD_ARGS: "--workers=2 --threads=2"

resources:
  requests:
    cpu: "250m"
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 2Gi

livenessProbe:
  initialDelaySeconds: 180
  periodSeconds: 10
  failureThreshold: 10

readinessProbe:
  initialDelaySeconds: 180
  periodSeconds: 10
  failureThreshold: 10