# ==========================================
# PROMETHEUS COST-OPS CONFIGURATION (EKS)
# ==========================================
alertmanager:
  enabled: false 

pushgateway:
  enabled: false 

server:
  global:
    scrape_interval: 15s 
  
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: "gp2"

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true