# =====================================================================
# REDPANDA VALUES (ENGINE + CONSOLE) - AWS EKS SPOT OPTIMIZED
# =====================================================================
statefulset:
  replicas: 3 # Prod-ready, but we run on Spot

config:
  cluster:
    auto_create_topics_enabled: false
    default_topic_replications: 3 # Safe replication

resources:
  cpu:
    cores: 1
  memory:
    container:
      max: 2.5Gi

storage:
  persistentVolume:
    enabled: true
    storageClass: "gp2" # 🔥 AWS EBS Default
    size: 20Gi

# 🔥 CONSOLE MERGED HERE!
console:
  enabled: true
  config:
    kafka:
      brokers: ["redpanda-0.redpanda.uds-production.svc.cluster.local:9093"]
  service:
    type: ClusterIP # Di EKS, NodePort bahaya. Pakai ClusterIP lalu port-forward.