# =====================================================================
# REDPANDA CONSOLE VALUES - THE DASHBOARD
# =====================================================================
config:
  kafka:
    # 🔥 FIX: Ganti port ke 9093 untuk jalur internal K8s
    brokers: ["redpanda-0.redpanda.uds-production.svc.cluster.local:9093"]

service:
  type: NodePort
  nodePort: 30080