# =====================================================================
# RISINGWAVE VALUES - REAL-TIME STREAMING DB (HETZNER VPS OPTIMIZED)
# =====================================================================
tags:
  etcd: true
  minio: true # Embedded MinIO ini dibiarkan khusus HANYA untuk internal state RisingWave
  postgresql: true

etcd:
  persistence:
    enabled: true
    storageClass: "local-path"

minio:
  persistence:
    enabled: true
    storageClass: "local-path"

postgresql:
  primary:
    persistence:
      enabled: true
      storageClass: "local-path"

# 🔥 BLOK CONSOLE DIHAPUS: 
# Udah di-handle mutlak pakai kubernetes_service di data_stack.tf nembak port 5691

metaNode:
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

computeNode:
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

frontendNode:
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

compactorNode:
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi