# =====================================================================
# TEMPORAL VALUES - THE CONTROL PLANE (AWS EKS OPTIMIZED)
# =====================================================================
server:
  replicaCount: 2 # HA on Spot
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  config:
    persistence:
      defaultStore: default
      visibilityStore: visibility
      datastores:
        default:
          sql:
            pluginName: postgres12
            driverName: postgres12
            databaseName: temporal
            connectAddr: temporal-postgresql.uds-production.svc.cluster.local:5432
            connectProtocol: tcp
            user: temporal
            password: temporal-dev-password
            manageSchema: true
        visibility:
          sql:
            pluginName: postgres12
            driverName: postgres12
            databaseName: temporal_visibility
            connectAddr: temporal-postgresql.uds-production.svc.cluster.local:5432
            connectProtocol: tcp
            user: temporal
            password: temporal-dev-password
            manageSchema: true

# Sisanya sama seperti master, hanya RAM/CPU dinaikkan sedikit.
internal-frontend:
  resources: { requests: { cpu: 100m, memory: 256Mi }, limits: { cpu: 500m, memory: 512Mi } }
history:
  resources: { requests: { cpu: 100m, memory: 256Mi }, limits: { cpu: 500m, memory: 512Mi } }
matching:
  resources: { requests: { cpu: 100m, memory: 256Mi }, limits: { cpu: 500m, memory: 512Mi } }
worker:
  resources: { requests: { cpu: 100m, memory: 256Mi }, limits: { cpu: 500m, memory: 512Mi } }