version: '3.8'

services:
  # SHARD 1
  postgres-shard-1:
    image: postgres:15
    container_name: postgres-shard-1
    command: ["postgres", "-c", "wal_level=logical"] 
    environment:
      POSTGRES_USER: epocket_admin
      POSTGRES_PASSWORD: epocket_password
      POSTGRES_DB: epocket_ledger
    ports:
      - "5431:5432"
    volumes:
      - ./01-epocket-ledger.sql:/docker-entrypoint-initdb.d/01-epocket-ledger.sql
    networks:
      - zona1-network

  # SHARD 2
  postgres-shard-2:
    image: postgres:15
    container_name: postgres-shard-2
    command: ["postgres", "-c", "wal_level=logical"]
    environment:
      POSTGRES_USER: epocket_admin
      POSTGRES_PASSWORD: epocket_password
      POSTGRES_DB: epocket_ledger
    ports:
      - "5432:5432"
    volumes:
      - ./01-epocket-ledger.sql:/docker-entrypoint-initdb.d/01-epocket-ledger.sql
    networks:
      - zona1-network

  # SHARD 3
  postgres-shard-3:
    image: postgres:15
    container_name: postgres-shard-3
    command: ["postgres", "-c", "wal_level=logical"]
    environment:
      POSTGRES_USER: epocket_admin
      POSTGRES_PASSWORD: epocket_password
      POSTGRES_DB: epocket_ledger
    ports:
      - "5433:5432"
    volumes:
      - ./01-epocket-ledger.sql:/docker-entrypoint-initdb.d/01-epocket-ledger.sql
    networks:
      - zona1-network

networks:
  zona1-network:
    name: zona1-network
    driver: bridge